server {
    listen 80;
    server_name {{DOMAIN}};

    root {{ROOT_PATH}}/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Static asset cache (optional)
    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|webp|woff2?)$ {
        expires 30d;
        access_log off;
        try_files $uri =404;
    }
}